ref_dict = ['Twenty_four_arch_RH_solids', 'Twenty_four_arch_EXT_RH_solids',
                'Thirty_six_arch_RH_solids', 'Fourty_two_solids',
                'Eighteen_arch_RH_solids', 'Thirty_arch_RH_solids', 'Fifty_four_arch_RH_solids',
                'Sixty_arch_RH_solids', 'Twenty_four_fairing_arch_RH_solids',
                'Thirty_six_fairing_arch_RH_solids', 'Fourty_two_fairing_arch_RH_solids',
                'Fourty_eight_fairing_arch_RH_solids', 'Twenty_four_arch_RH_solids_pr',
                'Twenty_four_arch_EXT_RH_solids_pr', 'Eighteen_arch_RH_solids_pr',
                'Thirty_arch_RH_solids_pr', 'Thirty_six_arch_RH_solids',
                'Fifty_four_arch_RH_solids_pr', 'Sixty_arch_RH_solids_pr',
                'Twenty_four_fairing_arch_RH_solids_pr', 'Thirty_six_fairing_arch_RH_solids_pr',
                'Fourty_two_fairing_arch_RH_solids_pr', 'Fourty_eight_fairing_arch_RH_solids_pr',
                'Twenty_four_arch_LH_solids', 'Twenty_four_arch_EXT_LH_solids',
                'Thirty_six_arch_LH_solids', 'Fourty_two_solids', 'Eighteen_arch_LH_solids',
                'Thirty_arch_LH_solids', 'Fifty_four_arch_LH_solids', 'Sixty_arch_LH_solids',
                'Twenty_four_fairing_arch_LH_solids', 'Thirty_six_fairing_arch_LH_solids',
                'Fourty_two_fairing_arch_LH_solids', 'Fourty_eight_fairing_arch_LH_solids',
                'Twenty_four_arch_LH_solids_pr', 'Twenty_four_arch_EXT_LH_solids_pr',
                'Eighteen_arch_LH_solids_pr', 'Thirty_arch_LH_solids_pr', 'Thirty_six_arch_LH_solids',
                'Fifty_four_arch_LH_solids_pr', 'Sixty_arch_LH_solids_pr',
                'Twenty_four_fairing_arch_LH_solids_pr', 'Thirty_six_fairing_arch_LH_solids_pr',
                'Fourty_two_fairing_arch_LH_solids_pr', 'Fourty_eight_fairing_arch_LH_solids_pr',
                'Twenty_four_DR3_LH_solids', 'Twenty_four_DR3_RH_solids', 'Twenty_four_solids',
                'Twenty_four_EXT_DR3_LH_solids', 'Twenty_four_EXT_DR3_RH_solids',
                'Thirty_six_DR3_solids', 'Thirty_six_DR3_solids', 'Thirty_six_solids',
                'Fourty_two_solids', 'Fourty_eight_horseshoe_solids_LH',
                'Fourty_eight_horseshoe_solids_RH', 'Fourty_eight_solids',
                'Twelve_solids', 'Eighteen_solids', 'Thirty_solids', 'Fifty_four_solids',
                'Sixty_solids', 'Seventy_two_solids', 'Twenty_four_fairing_solids',
                'Thirty_six_fairing_solids', 'Fourty_two_fairing_solids',
                'Fourty_eight_fairing_solids', 'Twenty_four_DR3_LH_solids_pr',
                'Twenty_four_DR3_RH_solids_pr', 'Twenty_four_solids_pr',
                'Twenty_four_EXT_DR3_LH_solids_pr', 'Twenty_four_EXT_DR3_RH_solids_pr',
                'Thirty_six_solids_pr', 'Fourty_two_solids_pr', 'Fourty_eight_horseshoe_solids_LH',
                'Fourty_eight_horseshoe_solids_RH', 'Fourty_eight_solids_pr',
                'Twelve_solids_pr', 'Eighteen_solids_pr', 'Thirty_solids',
                'Fifty_four_solids_pr', 'Sixty_solids_pr', 'Seventy_two_solids_pr',
                'Twenty_four_fairing_solids_pr', 'Thirty_six_fairing_solids_pr',
                'Fourty_two_fairing_solids_pr', 'Fourty_eight_fairing_solids_pr',
                'Twenty_four_solids_sec41', 'Fourty_two_solids_sec41', 'Fourty_eight_solids_sec41',
                'Twenty_four_solids_sec41_pr', 'Thirty_six_solids_sec41_pr',
                'Fourty_two_solids_sec41_pr', 'Fourty_eight_solids_sec41_pr',
                'Twenty_four_solids_sec47', 'Thirty_six_solids_sec47',
                'Fourty_two_solids_sec47', 'Fourty_eight_solids_sec47',
                'Twelve_solids_sec47', 'Eighteen_solids_sec47', 'Thirty_solids_sec47',
                'Twenty_four_fairing_solids_sec47', 'Thirty_six_fairing_solids_sec47',
                'Fourty_two_fairing_solids_sec47', 'Fourty_eight_fairing_solids_sec47']
